# Makefile for make_grid
# ======================
# Author: R.J.Barnes
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis
OBJS = test_aacgm.o
SRC=test_aacgm.c
DSTPATH = $(BINPATH)
OUTPUT = test_aacgm
LIBS=-laacgm.1
SLIB=-lm -lz
 

include $(MAKEBIN).$(SYSTEM)
